'use client'

import { useState } from 'react'
import { ArrowLeft, Check, FileText, Sparkles, Upload } from 'lucide-react'

export default function UploadNotesPage() {
 const [file,setFile]=useState<File|null>(null); const [status,setStatus]=useState('idle'); const [questions,setQuestions]=useState('10'); const [difficulty,setDifficulty]=useState('Mixed'); const [result,setResult]=useState<{mode:string;questions:unknown[]}|null>(null)
 const generate=async()=>{if(!file)return; setStatus('processing'); const sourceText=file.type==='text/plain'?await file.text():''; const response=await fetch('/api/assessment/generate',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({topic:'Sampling',count:Number(questions),difficulty,sourceText})}); const data=await response.json(); setResult(data); setStatus('ready')}
 return <main className="login-page onboarding"><div className="login-brand"><div className="brand-mark"><FileText size={20}/></div><span>StatSkill <b>AI</b></span></div><section className="onboarding-card notes-card"><button className="text-button" onClick={()=>window.location.assign('/')}><ArrowLeft size={14}/> Back to workspace</button><p className="eyebrow">SOURCE-GROUNDED LEARNING</p><h1>Upload your notes.</h1><p className="login-subtitle">Let StatSkill AI identify concepts and create a personalized assessment from your own study material.</p><label className="upload-drop"><Upload size={28}/><strong>{file?file.name:'Choose a document'}</strong><span>PDF, DOCX, TXT, or PPTX · max 10 MB</span><input type="file" accept=".pdf,.docx,.txt,.pptx" onChange={e=>setFile(e.target.files?.[0]||null)}/></label><div className="form-grid"><label>Competency / topic<select><option>Sampling</option><option>Python</option><option>Data Quality</option><option>Statistics</option></select></label><label>Questions<select value={questions} onChange={e=>setQuestions(e.target.value)}><option>5</option><option>10</option><option>15</option><option>20</option></select></label><label className="wide">Difficulty<select value={difficulty} onChange={e=>setDifficulty(e.target.value)}><option>Easy</option><option>Medium</option><option>Hard</option><option>Mixed</option></select></label></div>{status==='processing'&&<div className="processing"><strong>Analyzing your notes...</strong><span><Check size={14}/> Reading document</span><span><Check size={14}/> Identifying topics and concepts</span><span><Check size={14}/> Mapping competencies</span><span><Sparkles size={14}/> Generating and validating questions</span></div>}{status==='ready'&&<div className="ready"><strong>Quiz ready</strong><span>{result?.questions.length || questions} source-grounded MCQs generated in {result?.mode === 'ai' ? 'AI Mode' : 'Fallback Mode'}.</span><button className="primary-button" onClick={()=>window.location.assign('/')}>Take generated quiz</button></div>}{status==='idle'&&<button className="primary-button" disabled={!file} onClick={generate}>Generate quiz <Sparkles size={15}/></button>}<footer>Questions use uploaded material as context and show a source reference whenever available.</footer></section></main>
}
